SISGFRAN/UPC.SISGFRAN.Web/Controllers/SolicitanteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using UPC.SISGFRAN.BL.Repositorios;
using UPC.SISGFRAN.EL.Inherited;
using UPC.SISGFRAN.EL.NonInherited;
using UPC.SISGFRAN.Web.Helper.PdfReportGenerator;

namespace UPC.SISGFRAN.Web.Controllers
{
    public class SolicitanteController : PdfViewController
    {
        #region "Variables globales"
        SolicitanteBL solicitanteBL = new SolicitanteBL();
        #endregion

        public ActionResult Index(int page = 1, int pageSize = 10, string sort = "Id", string sortdir = "DESC")
        {
            SolicitudEL records = new SolicitudEL();
            ListaPaginada<SolicitudEL> listaContentSolicitante = new ListaPaginada<SolicitudEL>();

            string desc = string.Empty;
            List<SolicitudEL> listSolicitantes = solicitanteBL.GetSolicitantes();

            listaContentSolicitante.Content = listSolicitantes
                        .OrderBy(sort + " " + sortdir)
                        .Skip((page - 1) * pageSize)
                        .Take(pageSize)
                        .ToList();

            // Count
            listaContentSolicitante.TotalRecords = listSolicitantes.Count();
            listaContentSolicitante.CurrentPage = page;
            listaContentSolicitante.PageSize = pageSize;

            records.ListaSolicitudes = listaContentSolicitante;
            return View(records);
        }

        
        public ActionResult EvaluacionCrediticia(int id)
        {
            //ESTE ID QUE SE ESTÁ PASANDO ES DEL SOLICITANTE... AQUÍ DEBERÍA CONECTARSE CON EL SERVICIO
            string titulo = string.Empty;
            int solId = id;
             var a = new SolicitanteBL();
            SolicitanteEL solicitanteEval = a.SetResultadoEvaluacion(id);

            if (solicitanteEval != null)
            {
                //titulo = "Evaluación de la solicitud N° " + solicitudEval.NumSolicitud;
                //FillImageUrl(solicitudEval.ReporteEvaluacion, "logo_pc.jpeg");
                //return this.ViewPdf(titulo, "_ReporteEval", solicitudEval);

                TempData["id"] = id;
                TempData["msg"] = (solicitanteEval.FueAprobado ? "Solicitante Aprobado" : "Solicitante Rechazado");
                return RedirectToAction("Index");
            }
            else
            {
                TempData["msg"] = "No existe evaluación";
                return RedirectToAction("Index");
            }


        }


        public ActionResult RechazarSolicitud(int id)
        {
            var sel = new SolicitanteBL();
            sel.SetResultadoEvaluacion(id, true);

            return RedirectToAction("Index");
        }

        #region Metodos

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        private void FillImageUrl(ReporteEvaluacionEL reporte, string imageName)
        {
            string url = string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~"));
            reporte.ImageUrl = url + "Content/Images/" + imageName;
        }

        public JsonResult EvaluacionCredito(string solicitante)
        {
            try
            {
                int idSolicitud = Convert.ToInt32(solicitante);
                SolicitudEL oSolicitante;

                //Obtener datos de la solicitud a Evaluar
                oSolicitante = solicitanteBL.GetSolicitante(idSolicitud);
                string strRiesgo;
                strRiesgo = CalcularRiesgoEco(oSolicitante.NumeroDocumento);

                return Json(new { status = true, message = "", nombre = oSolicitante.Solicitante.NombreCompleto, capital = oSolicitante.MontoCapital, riesgo = strRiesgo }, JsonRequestBehavior.AllowGet);
 
            }
            catch (Exception ex)
            {
                return Json(new { status = false, message = ex.Message.ToString() }, JsonRequestBehavior.AllowGet);
            }
        }

        private string CalcularRiesgoEco(string dni)
        {
            string resultado = "";
            switch (dni)
            {
                case "45792117": resultado = "Bajo riesgo, No reporta información de deudas"; break;
                case "40404548": resultado = "Mediano Riesgo, Deudas con poco atraso"; break;
                case "10444478981": resultado = "Alto Riesgo, Deudas con atraso significativo"; break;
                case "10445278981": resultado = "Mínimo Riesgo, Sin deudas vencidas"; break;
                case "65523322": resultado = "Bajo riesgo, No reporta información de deudas"; break;
                default:
                    break;
            }
            return resultado;
        }

        #endregion

    }
}

SISGFRAN/UPC.SISGFRAN.Web/Controllers/SolicitudController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic;
using System.Web;
using System.Web.Security;
using UPC.SISGFRAN.Web.Helper;
using UPC.SISGFRAN.EL.Comunes;
using UPC.SISGFRAN.EL.Inherited;
using UPC.SISGFRAN.BL.Repositorios;
using UPC.SISGFRAN.WS.Repositorios;
using UPC.SISGFRAN.EL.NonInherited;
using UPC.SISGFRAN.Web.Helper.PdfReportGenerator;
using System.Web.Mvc;
using System.Configuration;
using System.Text;
using UPC.SISGFRAN.Web.Helper.Mail;

namespace UPC.SISGFRAN.Web.Controllers
{
    public class SolicitudController : PdfViewController
    {
        #region "Variables globales"
        SolicitudBL solicitudBL = new SolicitudBL();
        EvaluadorWS evaluadorClient = new EvaluadorWS();
        #endregion

        //
        // GET: /Solicitud/
        public ActionResult Index(int page = 1, int pageSize = 10, string sort = "Id", string sortdir = "DESC")
        {
            SolicitudEL records = new SolicitudEL();
            ListaPaginada<SolicitudEL> listaContentSolicitud = new ListaPaginada<SolicitudEL>();

            string desc = string.Empty;
            List<SolicitudEL> listSolicitudesPendientes = solicitudBL.GetSolicitudesPendientes(desc);

            listaContentSolicitud.Content = listSolicitudesPendientes
                        .OrderBy(sort + " " + sortdir)
                        .Skip((page - 1) * pageSize)
                        .Take(pageSize)
                        .ToList();

            // Count
            listaContentSolicitud.TotalRecords = listSolicitudesPendientes.Count();
            listaContentSolicitud.CurrentPage = page;
            listaContentSolicitud.PageSize = pageSize;

            records.ListaSolicitudes = listaContentSolicitud;
            return View(records);
        }

        [HttpGet]
        public ActionResult BuscarSolicitud(string desc = null, int page = 1, int pageSize = 10, string sort = "Id", string sortdir = "DESC")
        {
            try
            {
                SolicitudEL records = new SolicitudEL();
                desc = (desc == null ? "" : desc);
                ViewBag.desc = desc;

                ListaPaginada<SolicitudEL> listaContentSolicitud = new ListaPaginada<SolicitudEL>();

                List<SolicitudEL> listSolicitudesPendientes = solicitudBL.GetSolicitudesPendientes(desc);

                listaContentSolicitud.Content = listSolicitudesPendientes
                            .OrderBy(sort + " " + sortdir)
                            .Skip((page - 1) * pageSize)
                            .Take(pageSize)
                            .ToList();

                // Count
                listaContentSolicitud.TotalRecords = listSolicitudesPendientes.Count();
                listaContentSolicitud.CurrentPage = page;
                listaContentSolicitud.PageSize = pageSize;

                records.ListaSolicitudes = listaContentSolicitud;
                return PartialView("_Solicitud", records);
            }
            catch (Exception ex)
            {
                return Json(new { status = false, message = ex.Message.ToString() }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Exportar(int id)
        {
            string titulo = string.Empty;
            int solId = id;
            SolicitudEL solicitudEval = solicitudBL.GetResultadoEvaluacion(solId);

            if (solicitudEval != null)
            {
                titulo = "Evaluación de la solicitud N° " + solicitudEval.NumSolicitud;
                FillImageUrl(solicitudEval.ReporteEvaluacion, "logo_pc.jpeg");
                return this.ViewPdf(titulo, "_ReporteEval", solicitudEval);
            }
            else
            {
                TempData["msg"] = "No existe evaluación";
                return RedirectToAction("Index");
            }
            
        }

        [HttpGet]
        public ActionResult EnviarCorreo(string id, string fecha, string hora, string correo)
        {
            try
            {
                int idSol = Convert.ToInt32(id);
                SolicitudEL oSolicitud = solicitudBL.GetSolicitudById(idSol);

                // Configurar envio de correo
                string subject = string.Format("{0}: {1} - {2}", ConfigurationManager.AppSettings.Get("AsuntoMail"), "Pardos Chicken", DateTime.Now.ToString("dd / MMM / yyy hh:mm:ss"));
                string mailFrom = ConfigurationManager.AppSettings.Get("MailEmisor");
                string passwordMailEmisor = ConfigurationManager.AppSettings.Get("PasswordMailEmisor");
                StringBuilder buffer = new StringBuilder();
                buffer.Append("Estimado <b>{0} {1}, {2} </b> ");
                buffer.Append(" Es grato saludarlo e informarle que se le convoca a una entrevista en nuestra oficina principal<br />");
                buffer.Append(" Fecha:" + fecha + " <br/><br/>");
                buffer.Append(" Hora:" + hora + "<br/><br/>");
                buffer.Append(" Saludos cordiales. <br/><br/>");
                buffer.Append("<i> Nota: Por favor no responda este correo. <i>");


                MailHelper.SendMail(mailFrom, passwordMailEmisor, correo, subject, string.Format(buffer.ToString(), oSolicitud.Solicitante.ApellidoPaterno, oSolicitud.Solicitante.ApellidoMaterno, oSolicitud.Solicitante.Nombres), true, System.Net.Mail.MailPriority.Normal);


                return Json(new { status = true, message = "Se envió correctamente el correo." }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { status = false, message = ex.Message.ToString() }, JsonRequestBehavior.AllowGet);
            }
        }

        #region Metodos

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        private void FillImageUrl(ReporteEvaluacionEL reporte, string imageName)
        {
            string url = string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~"));
            reporte.ImageUrl = url + "Content/Images/" + imageName;
        }

        public JsonResult Evaluar(string solicitud)
        {
            try
            {
                SolicitudEL solictudEvaluada = null;
                ReporteEvaluacionEL resultado;
                int oEstado = -1;
                int idSolicitud = Convert.ToInt32(solicitud);

                //Obtener datos de la solicitud a Evaluar
                solictudEvaluada = solicitudBL.GetSolicitudById(idSolicitud);

                SolicitudEL solicitudActualizada;
                // Enviar al servicio web a evaluar
                resultado = evaluadorClient.EvaluarSolicitud(solictudEvaluada);
                resultado.UsuarioCreacion = SesionUsuario.Usuario.Id;

                if (resultado.Resultado)
	            {
		            oEstado = (int)Constantes.EstadoSolicitud.Aprobada;
	            }
                else
	            {
                    oEstado = (int)Constantes.EstadoSolicitud.Rechazada;
	            }

                // Actualizar el estado de la solicitud
                ParametroEL estado = new ParametroEL(){ Codigo = oEstado };

                SolicitudEL oSolicitud = new SolicitudEL()
                {
                    Id = idSolicitud,
                    Estado = estado,
                    UsuarioModifica = SesionUsuario.Usuario.Id,
                    ReporteEvaluacion = resultado
                };

                solicitudActualizada = solicitudBL.Actualizar(oSolicitud);

                // Actualizar resultado del reporte para descargar el reporte.
                solicitudBL.RegistrarReporteEvaluacion(oSolicitud);

                if (resultado.Resultado) // true
                {
                    //Enviar Nombre, Correo, 
                    return Json(new { status = true, message = "La solicitud de franquicia seleccionada ha sido aprobada.", Solicitante = solicitudActualizada.Solicitante.NombreCompleto, Email = solicitudActualizada.Solicitante.Email }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { status = false, message = "La solicitud de franquicia seleccionada ha sido rechazada" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { status = false, message = ex.Message.ToString() }, JsonRequestBehavior.AllowGet);
            }

        }


        #endregion

	}
}

SISGFRAN/UPC.SISGFRAN.Web/Views/Solicitante/Index.cshtml
@{
    ViewBag.Title = "Evaluar solicitante";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    var message = TempData["msg"] ?? string.Empty;
    var id = TempData["id"] ?? string.Empty;
}

<!-- Paneles -->
<div class="container2">
    <div class="margenPanelRigth">
        <fieldset>
            <legend>Explorador de Solicitantes de Franquicia</legend>
            <div class="form-group row OcultarDiv">
                <input type="hidden" value="" id="hddCodSolicitud" name="hddCodSolicitud">
            </div>
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="fa fa-table"></i> Listado de solicitantes a evaluar</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div id="gridSolicitud">
                                @Html.Partial("_solicitud")
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br />
            <div class="form-group row col-md-3">
                    <span class="input-group-btn" style="padding-left:5px;">
                        <a class="btn btn-success" href='#' onclick="EvaluarSolicitante();" id='btnEvaluarSolicitante' title='Evaluar Solicitante'>
                            <span class='glyphicon glyphicon-tasks'>
                                Evaluar Solicitante
                            </span>
                        </a>
                    </span>
                </div>
        </fieldset>
    </div>
</div>

<div class="modal fade in" id="mReporteCrediticio">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h2 class="modal-title">Reporte Crediticio</h2>
            </div>
                <div class="modal-body">

                    <div class="container">
                        <ul class="nav nav-tabs">
                            <li class="active"><a data-toggle="tab" href="#menu1">Datos del solicitante</a></li>
                        </ul>
                        <div class="tab-content">
                            <div id="menu1" class="tab-pane fade in active">
                                <label>Solicitante</label>
                                <input type="text" class="form-control" id="nomSolicitante" />
                                <label>Capital</label>
                                <input type="text" class="form-control" value="0" id="capital" />
                                <label>Riesgo</label>
                                <input type="text" class="form-control" id="txtRiesgo" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-danger" type="button" data-dismiss="modal">Cerrar</button>
                </div>
        </div>
    </div>
</div>

<div class="modal fade in" id="mEvaluar">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h2 class="modal-title">Evaluar Solicitante</h2>
            </div>
            @using (Html.BeginForm("EvaluacionCrediticia", "Solicitante", FormMethod.Get))
            {
                <div class="modal-body">
                    <div class="container">
                        <ul class="nav nav-tabs">                        
                            <li class="active" ><a data-toggle="tab" href="#menu1">Datos Reniec</a></li>
                            <li><a data-toggle="tab" href="#menu2">Información Financiera</a></li>                        
                        </ul>

                        <div id="myTabContent" class="tab-content">
                            <div id="menu1" class="tab-pane fade active in">
                                <h2></h2>
                                <input type="hidden" id="id" name="id" />
                                <label>Número Documento</label>
                                <input type="text" class="form-control" id="NroDoc" />
                                <label>Nombres y Apellidos</label>
                                <input type="text" class="form-control" id="NombreCompleto" />
                                <label>Fecha de Nacimiento</label>
                                <input type="text" class="form-control" id="FechNacimiento" />
                                <label>Sexo</label>
                                <input type="text" class="form-control" id="Sexo" />
                                <label>Grado de Instrucción</label>
                                <input type="text" class="form-control" id="GradoInstruccion" />
                            </div>
                            <div id="menu2" class="tab-pane fade">
                                <h2></h2>
                                <label>Salario</label>
                                <input type="text" class="form-control" id="Salario" />
                                <label>Gastos</label>
                                <input type="text" class="form-control" id="Gastos" />
                                <label>Cargo</label>
                                <input type="text" class="form-control" id="Cargo" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="btnEvaluar" class="btn btn-success"  type="submit">Enviar a evaluación crediticia</button>
                </div>
            }
        </div>
    </div>
</div>

<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">

        $(document).ready(function () {
            
        });

        function SolicitudSelected(radio) {
            if ($(radio).is(':checked')) {
                var codSol = $(radio).val();
                $("#hddCodSolicitud").val(codSol);
                var urlExportar = "/Solicitante/EvaluacionCrediticia/" + codSol;
                $("a#btnEvaluacionCrediticia").attr("href", urlExportar);
            } else {
                $("#hddCodSolicitud").val("");
                $("a#btnEvaluacionCrediticia").attr("href", "#");
            }
        }

        function EvaluarSolicitante() {
            var solicitud = $("#hddCodSolicitud").val();
            
            if (solicitud == "") {
                bootbox.alert({
                    message: "Seleccione solicitante a evaluar",
                    size: 'small'
                });
                return;
            } else {


                if (solicitud === "45792117") {
                    bootbox.alert({
                        message: "Verificación incorrecta",
                        size: 'small',
                        buttons: {
                            ok: {
                                label: 'Rechazar solicitud'
                            }
                        },
                        callback: function () {

                            var id = $("#id_" + solicitud).val();
                            $.ajax({
                                url: 'RechazarSolicitud',
                                type: 'GET',
                                data: { id: id },
                                success: function (valid) {
                                 
                                }
                            });
                            location.reload();
                        }
                    });

                    return;
                }

                bootbox.alert("Verificación Correcta"
                , function () {                    
                    $('#mEvaluar').modal('show');
                    $("#NroDoc").val($("#num_" + solicitud).text());
                    $("#NombreCompleto").val($("#nom_" + solicitud).text());
                    $("#FechNacimiento").val($("#fecha_" + solicitud).text());
                    $("#Sexo").val($("#sexo_" + solicitud).text());
                    $("#GradoInstruccion").val($("#grad_" + solicitud).text());
                    $("#Salario").val($("#ing_" + solicitud).text());
                    $("#Gastos").val($("#gast_" + solicitud).text());
                    $("#Cargo").val($("#cargo_" + solicitud).text());
                    $("#id").val($("#id_" + solicitud).val());
                });

            }
        }
        
        function EvaluacionCrediticia() {
            var solicitud = $("#hddCodSolicitud").val();
        }

        function VerReporte(solicitante)
        {
            $.ajax({
                url: "/Solicitante/EvaluacionCredito",
                type: "GET",
                data: { solicitante: solicitante },
                dataType: "html",
                traditional: true,
                cache: false,
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    var datos = jQuery.parseJSON(data);
                    if (datos.status == true) {
                        $("#nomSolicitante").val(datos.nombre);
                        $("#capital").val(datos.capital);
                        $("#txtRiesgo").val(datos.riesgo);
                    } else {
                        bootbox.alert({
                            message: datos.message,
                            size: 'small'
                        });
                        return false;
                    }
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    bootbox.alert('error', textStatus, 'Error');
                }
            });
        }

    </script>

    <script type="text/javascript">
        var message = '@message';
        if (message)
            bootbox.alert(message);

        var id = '@id';
        if (id) {
            VerReporte(id);
            $("#mReporteCrediticio").modal('show');
        }

    </script>
}

SISGFRAN/UPC.SISGFRAN.Web/Views/Solicitante/_Solicitud.cshtml
@model UPC.SISGFRAN.EL.Inherited.SolicitudEL

<div>
    @{
        var grid = new WebGrid(
                    canPage: true,
                    rowsPerPage: Model.ListaSolicitudes.PageSize,
                    canSort: false,
                    ajaxUpdateContainerId: "gridSolicitud");
        grid.Bind(Model.ListaSolicitudes.Content, rowCount: Model.ListaSolicitudes.TotalRecords, autoSortAndPage: false);
        grid.Pager(WebGridPagerModes.All,
                    firstText: "<<", lastText: ">>",
                    previousText: "<",
                    nextText: ">",
                    numericLinksCount: 15);
                    @grid.GetHtml(htmlAttributes: new { id = "gridSolicitud1" },
            tableStyle: "webgrid",
            headerStyle: "webgrid-header",
            footerStyle: "webgrid-footer",
            alternatingRowStyle: "webgrid-alternating-row",
            selectedRowStyle: "webgrid-selected-row",
            rowStyle: "webgrid-row-style",
            fillEmptyRows: false,
            mode: WebGridPagerModes.All,
            columns: grid.Columns(
                 grid.Column(format: @<text><input id="NumeroDocumento" class="chkRbSol" name="NumeroDocumento" type="radio" value="@item.NumeroDocumento" onclick="javascript: SolicitudSelected(this)" /></text>),
                 grid.Column("Solicitante.NombreCompleto", "Solicitante", format: @<text><input type="hidden" id="id_@item.NumeroDocumento" value="@item.Solicitante.Id" /><span class="nom_@item.Id" id="nom_@item.NumeroDocumento">@item.Solicitante.NombreCompleto</span></text>),
                 grid.Column("Solicitante.TipoDocumento.Nombre", "Tipo Documento"),
                 grid.Column("NumeroDocumento", "Nro. Documento", format: @<text><span id="num_@item.NumeroDocumento">@item.NumeroDocumento</span></text>),
                 grid.Column("Solicitante.TituloObtenido", "Grado de Instrucción", format: @<text><span id="grad_@item.NumeroDocumento">@item.Solicitante.TituloObtenido</span></text>),
                 grid.Column("Solicitante.Sexo.Nombre", "Sexo", format: @<text><span id="sexo_@item.NumeroDocumento">@item.Solicitante.Sexo.Nombre</span></text>),
                 grid.Column("Solicitante.MontoIngresosMes", "Salario", format: @<text><span id="ing_@item.NumeroDocumento">@item.Solicitante.MontoIngresosMes</span></text>),
                 grid.Column("Solicitante.MontoGastosMes", "Gastos", format: @<text><span id="gast_@item.NumeroDocumento">@item.Solicitante.MontoGastosMes</span></text>),
                 grid.Column("Solicitante.Cargo", "Cargo", format: @<text><span id="cargo_@item.NumeroDocumento">@item.Solicitante.Cargo</span></text>),
                 grid.Column("Solicitante.FechaNacimiento", "Fecha Nacimiento", format: @<text><span id="fecha_@item.NumeroDocumento">@String.Format("{0:dd-MM-yyyy}", @item.Solicitante.FechaNacimiento)</span></text>, style: "col-md-1")
                
 ));
}

</div>